### ISSUE TITLE
[Documentação #9] - Implementação do Story Map na plataforma de desenvolvimento da UnB

### ISSUE THREAD

**Issue by G0ndim** [unb-mds/Squad09-UnBHUB#20]

**Comment by luccameds** [comment]
## Implementação do Story Map na plataforma de desenvolvimento da UnB 

![StoryMap](https://github.com/unb-mds/Squad09-UnBHUB/assets/63163895/4b00c407-b10f-4f11-bc29-276e73e018ae)
Link do projeto para melhor visualização: https://miro.com/app/board/uXjVKQTq3Zw=/

### Descrição:

Olá equipe,

Estou criando esta issue para acompanhar a implementação do story map para nossa plataforma de desenvolvimento destinada aos estudantes da Universidade de Brasília (UnB). Abaixo está um resumo do story map que elaboramos:

#### Themes:
1. **Autenticação:** Garantir que os usuários possam se autenticar de forma segura na plataforma utilizando o Firebase Authentication.
2. **Serviços:** Oferecer uma variedade de serviços úteis para os usuários, como acesso ao cardápio e calendário acadêmico.
3. **Salvamentos:** Permitir que os usuários salvem informações importantes para referência futura.

#### Epics:
1. **Cadastro e conexão na conta de usuário:** Permitir que os usuários se cadastrem e se conectem à plataforma.
2. **Cardápio:** Disponibilizar informações sobre o cardápio do Restaurante Universitário da UnB.
3. **Calendário:** Oferecer um calendário acadêmico com eventos importantes.
4. **Informações de usuários:** Permitir que os usuários visualizem e atualizem suas informações pessoais na plataforma.

#### User Stories:
- Entrar na plataforma e criar uma conta.
- Após o cadastro, o usuário é redirecionado para a página de autenticação (SignInScreen).
- O usuário pode visualizar o cardápio e selecionar o dia que deseja buscar para informa-se das refeições diárias.
- O usuário pode navegar pelo calendário e ver os eventos acadêmicos.
- O usuário pode atualizar suas informações de perfil, como uma data importante no calendário.

#### Próximos Passos:
1. **Priorização de User Stories:** Priorizar as user stories com base na importância e na viabilidade.
2. **Atribuição de Tarefas:** Atribuir tarefas específicas a membros da equipe para implementar as user stories.
3. **Desenvolvimento e Testes:** Desenvolver as funcionalidades conforme especificado nas user stories e realizar testes para garantir o bom funcionamento.

Vamos usar esta issue para acompanhar o progresso da implementação do story map e discutir qualquer dúvida ou problema que surgir durante o processo. Fiquem à vontade para adicionar comentários e atualizações conforme avançamos.
