### ISSUE TITLE
[Firebase #6] - Monitoramento e Manutenção

### ISSUE THREAD

**Issue by G0ndim** [unb-mds/Squad09-UnBHUB#26]
- [x] Estabelecer práticas de monitoramento para acompanhar o desempenho e a integridade da integração do Firebase após a implantação.
- [x] Fornecer suporte contínuo e manutenção conforme necessário para garantir que a integração do Firebase continue funcionando de maneira eficaz.

**Comment by antonioscarvalho** [comment]
As pessoas designadas para o levantamento do banco de dados estão em monitoramento e manutenção contantes do próprio.
